# Site settings
title: Mischa Nistl, DJ
description: "... aus Leidenschaft"
email: mischa.nistl@web.de
url: http://www.djmischanistl.de

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Mischa Nistl

# Social networks usernames
social:
  - title: instagram
    url: https://www.instagram.com/djmischanistl
  - title: facebook
    url: https://www.facebook.com/mischa.nistl
  - title: soundcloud
    url: https://soundcloud.com/djmischanistl

# Build settings
markdown: kramdown
permalink: pretty
